name: Build

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
    build:
      name: Flutter-Linux-Arm64
      runs-on: ubuntu-22.04-arm
    
      steps:
        - uses: actions/checkout@v4
          name: Repository checkout
          with:
            fetch-depth: 0
            submodules: true
            path: git

        # Only here so it doesn't whine about it being missing when running "doctor"
        - run: |
            sudo apt install libgtk-3-dev

        - name: Run fluttter doctor
          run: |
            ./git/flutter/bin/flutter doctor

        - name: Upload artifact
          uses: actions/upload-artifact@v4
          with:
            name: flutter_sdk_arm64_${{ runner.os }}
            path: ${{ github.workspace }}/git